### ISSUE TITLE
Gebruiker Heijmans en Servicehut moeten uit de groep 'users'

### ISSUE THREAD

**Issue by jebr** [jebr/System-Setup-Program-SSP#8]

**Comment by jebr** [comment]
NET LOCALGROUP "Users" "Heijmans" /delete 
NET LOCALGROUP "Users" "Servicehut" /delete 

De bovenstaande gebruikers worden uit de groep users gehaald, zowel in een NL OS als in een EN OS.

**Comment by technl** [comment]
Goed bezig :)
